### ISSUE TITLE
http proxy

### ISSUE THREAD

**Issue by dawnofman** [ysangkok/browser-http-proxy#1]
@ysangkok I have a situation - a v86 emulated VM runs an Apache web server, it should serve dynamically to webapp outside VM to host browser. I used [websockproxy](https://github.com/benjamincburns/websockproxy) to expose websocket 8080 port. Neither I can access the VM IP address/ webserver outside VM due to limitations. [websockify](https://github.com/novnc/websockify) and http proxy also doesn't help much. Any suggestion?

**Comment by ysangkok** [comment]
I don't understand the scenario, and I don't know what you're trying to achieve. But I think it would be best if you wrote a super-detailed question and put it on StackOverflow. It's not really related to the specific code in this project.

**Comment by dawnofman** [comment]
@ysangkok I am trying to achieve this. https://github.com/benjamincburns/websockproxy/issues/1#issue-55671215.

An Apache webserver inside the jork1 VM serves the website to public URL outside VM.
